Fix BR2_PACKAGE_BINUTILS_TARGET build
Summary:
In a cross-compilation context, during binutils install to target,
libtool tries to relink libctf and fail with
ERROR: unsafe header/library path used in cross-compilation: '-L/usr/lib'

Cause:
There is a bug in libtool 2.2.7a (embedded with binutils).
During relink phase, a search path relative to host (-L/usr/lib)
can be wrongfully inserted in gcc linking command.
In a cross-compilation context, search paths should always be
relative to target environment i.e -L$inst_prefix_dir$libdir.

Solution:
- Provide a patch for libtool v2.2.7 removing the problematic
  host search path.
- Force binutils autoreconf and apply the patch.

Test Plan: Required to run musl libc-test

Reviewers: O51 Linux Coolidge!

Subscribers: #linux_coolidge_cc

Differential Revision: https://phab.kalray.eu/D17905